base: &base
  adapter: postgresql
  encoding: unicode
  pool: 5

production:
  <<: *base
  database: <%= Rails.application.credentials.dig(:digitalocean, :db, :database) %>
  username: <%= Rails.application.credentials.dig(:digitalocean, :db, :username) %>
  password: <%= Rails.application.credentials.dig(:digitalocean, :db, :password) %>
  host: <%= Rails.application.credentials.dig(:digitalocean, :db, :host) %>
  port: <%= Rails.application.credentials.dig(:digitalocean, :db, :port) %>

development:
  <<: *base
  database: melzi_development
  username: ahb
  password:
  timeout: 5000

test:
  <<: *base
  database: melzi_test
  username: ahb
  password:
  timeout: 5000