development:
  url: <%= Rails.application.credentials.dig(:digitalocean, :db, :development, :postgresql, :url) %>

test:
  url: <%= Rails.application.credentials.dig(:digitalocean, :db, :test, :postgresql, :url) %>

production:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>