default&:
  adapter: postgresql

development:
  <<: default*
  url: <%= Rails.application.credentials.dig(:digitalocean, :db, :development, :postgresql, :url) %>

test:
  <<: default*
  url: <%= Rails.application.credentials.dig(:digitalocean, :db, :test, :postgresql, :url) %>

production:
  <<: default*
  url: <%= ENV["DATABASE_URL"] %>